### ISSUE TITLE
How to deal with attributes with '_' at beginning of name?

### ISSUE THREAD

**Issue by Lyndeno** [nix-community/haumea#14]
Besides using `liftDefault`?

For example, `_1password-gui`.

I will use default.nix for now just wondering if there is any other way to handle this?

**Comment by figsoda** [comment]
Currently there is no way to handle this, though you can specify the transformer to automatically rename the attributes

```nix
haumea.lib.load {
  src = ./src;
  transformer = _: mapAttrs' (name: nameValuePair
    (
      if elem (substring 0 1 name) (stringToCharacters "0123456789") then
        "_${name}"
      else
        name
    ));
}
```

**Comment by Lyndeno** [comment]
Perhaps a PR could be submitted to include this with the already included transformers

**Comment by figsoda** [comment]
Could you take a look at #17 and see how you think?
