### ISSUE TITLE
exclude specific directory names

### ISSUE THREAD

**Issue by MurdeRM3L0DY** [nix-community/haumea#21]
Would it be possible to specify a list of directory names to be ignored while scanning?

**Comment by figsoda** [comment]
You can prefix them with `_` to remove them from the final output (other files within the tree will still be able to access them), and with Nix's lazyness, haumea shouldn't run into any issues even if the files don't follow the format (e.g. contains invalid nix files)

**Comment by MurdeRM3L0DY** [comment]
gotcha, thanks.
