### ISSUE TITLE
Add more examples ?

### ISSUE THREAD

**Issue by drupol** [nix-community/haumea#42]
Hello,

I would like to use `haumea` in `inputs.home-manager.lib.homeManagerConfiguration { }` for the `modules` attributes.

From:

```nix
inputs.home-manager.lib.homeManagerConfiguration {
  modules = [
    ./modules/module1
    ./modules/module2
  ];
}
```

to 

```nix
inputs.home-manager.lib.homeManagerConfiguration {
  modules = inputs.haumea.lib.load { src = ./modules; };
}
```

I tried many things, but I have the feeling that it is not working.

Maybe I'm wrong? Can you help ?

**Comment by voobscout** [comment]
haumea outputs attributes, not lists.
given an src like "/modules/dir1/modulename.nix" it'll output
``` nix
{ dir1 = "modulename.nix"; }
```
in your particular case, it could be something like:

```nix
inputs.home-manager.lib.homeManagerConfiguration {
  modules =
    let  
      moduleFullNames = inputs.haumea.lib.load { src = ./modules; };
    in [ moduleFullNames.path.to.module moduleFullNames.another.path.to.module ];
}
```

**Comment by drupol** [comment]
Thank you.

**Comment by drupol** [comment]
What function do you use to get the path?

**Comment by drupol** [comment]
I just found out everything I need in https://github.com/nilp0inter/cafelito

Thank you @nilp0inter ! Really like your framework!!!
